### ISSUE TITLE
Yubikey AAGUIDs

### ISSUE THREAD

**Issue by hariria** [passkeydeveloper/passkey-authenticator-aaguids#38]
I was curious if there's a reason why Yubikey AAGUIDs are not included? Are these just tracking AAGUIDs for multi-device webauthn credentials?

Here are the Yubikey AAGUIDs for reference: https://support.yubico.com/hc/en-us/articles/360016648959-YubiKey-Hardware-FIDO2-AAGUIDs

**Comment by sbweeden** [comment]
My understanding is that Yubico has gone through certification and their information is well encapsulated in FIDO MDS. This repo was put together as a catchall for other authenticator AAGUIDs that have not gone through certification or cannot otherwise be listed in MDS because, for example, they don't support a verifiable attestation.

**Comment by timcappalli** [comment]
`aaguid.json` contains a list of passkey provider AAGUIDs
`combined_aaguid.json` is a merged list of `aaguid.json` + data from MDS which would include Yubikeys.
